# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  database: aticompanydb
  hostname: localhost
  pool: 5
  username: aticompanyuser
  password: 123456
  port: 5432
  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: aticompanydb
  hostname: localhost
  pool: 5
  username: aticompanyuser
  password: 123456
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: aticompanyuser
  hostname: localhost
  pool: 5
  username: aticompanyuser
  password: 123456
 

